#ifndef GPIOREGISTERMAP_H
#define GPIOREGISTERMAP_H

#define GPIOREGISTERMAP_OFFSET      0x200000

#define GPIOREGISTERMAP_MAPSIZE     0xF4

#define GPIOREGISTERMAP_GPFSEL0     0
#define GPIOREGISTERMAP_GPFSEL1     0x04
#define GPIOREGISTERMAP_GPFSEL2     0x08
#define GPIOREGISTERMAP_GPFSEL3     0x0C
#define GPIOREGISTERMAP_GPFSEL4     0x10
#define GPIOREGISTERMAP_GPFSEL5     0x14
#define GPIOREGISTERMAP_GPSET0      0x1c
#define GPIOREGISTERMAP_GPSET1      0x20
#define GPIOREGISTERMAP_GPCLR0      0x28
#define GPIOREGISTERMAP_GPCLR1      0x2C
#define GPIOREGISTERMAP_GPLEV0      0x34
#define GPIOREGISTERMAP_GPLEV1      0x38
#define GPIOREGISTERMAP_GPEDS0      0x40
#define GPIOREGISTERMAP_GPEDS1      0x44
#define GPIOREGISTERMAP_GPREN0      0x4C
#define GPIOREGISTERMAP_GPREN1      0x50
#define GPIOREGISTERMAP_GPFEN0      0x58
#define GPIOREGISTERMAP_GPFEN1      0x5C
#define GPIOREGISTERMAP_GPHEN0      0x64
#define GPIOREGISTERMAP_GPHEN1      0x68
#define GPIOREGISTERMAP_GPLEN0      0x70
#define GPIOREGISTERMAP_GPLEN1      0x74
#define GPIOREGISTERMAP_GPAREN0     0x7C
#define GPIOREGISTERMAP_GPAREN1     0x80
#define GPIOREGISTERMAP_GPAFEN0     0x88
#define GPIOREGISTERMAP_GPAFEN1     0x8C
#define GPIOREGISTERMAP_GPIO_PUP_PDN_CNTRL_REG0     0xE4
#define GPIOREGISTERMAP_GPIO_PUP_PDN_CNTRL_REG1     0xE8
#define GPIOREGISTERMAP_GPIO_PUP_PDN_CNTRL_REG2     0xEC
#define GPIOREGISTERMAP_GPIO_PUP_PDN_CNTRL_REG3     0xF0

#endif
